from setuptools import setup

APP = ["ngui.py"]
DATA_FILES = [
    ('', ['gfmdriver.py', 'gfm.py']),
]

OPTIONS = {
    'argv_emulation': True,
    'packages': [
        'aiofiles',
        'aiohttp',
        'aiosignal',
        'annotated-types',
        'anyio',
        'async-timeout',
        'attrs',
        'audioread',
        'bidict',
        'certifi',
        'cffi',
        'charset-normalizer',
        'click',
        'docutils',
        'exceptiongroup',
        'fastapi',
        'filelock',
        'frozenlist',
        'fsspec',
        'h11',
        'httpcore',
        'httptools',
        'httpx',
        'idna',
        'ifaddr',
        'itsdangerous',
        'jinja2',
        'joblib',
        'lazy-loader',
        'librosa',
        'llvmlite',
        'markdown2',
        'markupsafe',
        'mpmath',
        'msgpack',
        'multidict',
        'networkx',
        'nicegui',
        'numba',
        'numpy',
        'orjson',
        'packaging',
        'platformdirs',
        'pooch',
        'pscript',
        'pycparser',
        'pydantic',
        'pydantic-core',
        'pygments',
        'python-dotenv',
        'python-engineio',
        'python-multipart',
        'python-socketio',
        'pyyaml',
        'requests',
        'scikit-learn',
        'scipy',
        'setuptools',
        'simple-websocket',
        'sniffio',
        'sounddevice',
        'soundfile',
        'soxr',
        'starlette',
        'sympy',
        'threadpoolctl',
        'torch',
        'triton',
        'typing-extensions',
        'urllib3',
        'uvicorn',
        'uvloop',
        'vbuild',
        'watchfiles',
        'websockets',
        'wsproto',
        'yarl',
    ],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
